### ISSUE TITLE
Problematic with sdk

### ISSUE THREAD

**Issue by will702** [tibssy/Kivy-Android-Camera#1]
Hello Mr. Tibssy can you share your?bulldozer cause  i had a lot of errors when compiling cv2 thank you

**Comment by tibssy** [comment]
To fix this error:
Android SDK Tools: OpenCV requires Android SDK Tools revision 14 or newer.
Watch my video tutorial:

https://www.youtube.com/watch?v=c4tuSxSoERY
Made on Ubuntu 20.04 LTS

**Comment by will702** [comment]
thanks @tibssy  i appreciated it
