### ISSUE TITLE
Kivy App Crashes After Building 

### ISSUE THREAD

**Issue by GitProgrammerGuy32** [tibssy/Kivy-Android-Camera#6]
Kivy App crashes after opening on android..

**Comment by GitProgrammerGuy32** [comment]
@tibssy I tried running the kivy opencv app but nothing seemed to work please provide your email ID really need assistance!

**Comment by tibssy** [comment]
> @tibssy I tried running the kivy opencv app but nothing seemed to work please provide your email ID really need assistance!

@GitProgrammerGuy32 What is your logcat output?

**Comment by GitProgrammerGuy32** [comment]
Basically @tibssy I can provide You my python code with kivy and some buildozer changes I performed:

```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.image import Image
from kivy.graphics.texture import Texture
from kivy.clock import Clock
import cv2

class CameraApp(App):
    def build(self):
        # Create a layout to hold the camera widget
        layout = BoxLayout(orientation='vertical')

        # Create an OpenCV capture object
        self.capture = cv2.VideoCapture(0)

        # Create an Image widget to display the video stream
        self.image = Image()

        # Add the Image widget to the layout
        layout.add_widget(self.image)

        # Schedule the update function to be called every frame
        Clock.schedule_interval(self.update, 1.0 / 30.0)

        return layout

    def update(self, dt):
        # Read a frame from the camera
        ret, frame = self.capture.read()

        # Convert the frame to RGB format
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Update the Image widget with the new frame
        self.image.texture = self._frame_to_texture(frame)

    def _frame_to_texture(self, frame):
        # Convert the OpenCV frame to a texture that Kivy can display
        buffer = cv2.flip(frame, 0).tostring()
        texture = Texture.create(size=(frame.shape[1], frame.shape[0]), colorfmt='rgb')
        texture.blit_buffer(buffer, colorfmt='rgb', bufferfmt='ubyte')
        return texture

    def on_stop(self):
        # Release the camera when the application is stopped
        self.capture.release()

if __name__ == '__main__':
    from kivy.config import Config
    Config.set('graphics', 'width', '480')
    Config.set('graphics', 'height', '640')  # Set height to be larger than width for vertical orientation

    # Set the window orientation to vertical
    Config.set('graphics', 'orientation', 'portrait')

    # Disable multitouch emulation (since it's not applicable on mobile)
    Config.set('input', 'mouse', 'mouse,multitouch_on_demand')

    CameraApp().run()
```
and providing you my buildozer file important keylines:

`requirements = python3==3.7.6,hostpython3==3.7.6,kivy,pillow,opencv-python==4.8.0`
`osx.python_version = 3.7.6`
`android.permissions = CAMERA, (name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)`

So the above were the key elemnts of my buildozer file which I changed, was converting it to APK using google collab firstly which didn't seem to work then, I ran this using GitHub actions, for a **SIMPLE KIVY APP** code (Not including libraries and stuff), that seemed to work as well but as soon as I try with my camera code, my Buildozer pops up with some or the other, kindly try out your methodology using my code and please tell me what the issue is and certain changes which I would need to make. Hoping for a reply ASAP as I am near a deadline.

Regards
Shaurya Grover

**Comment by tibssy** [comment]
Hi @GitProgrammerGuy32,

Thank you for reaching out and sharing your code. It seems like you're attempting to access the camera on Android using `cv2.VideoCapture(0)`. However, for Android app development with Kivy, it's recommended to use the Kivy `Camera` widget for camera access.

In my repository, I've provided an example of how to access the camera on Android using the Kivy `Camera` widget. This approach is more suitable for Android and integrates seamlessly with the Kivy framework.

If you encounter any issues or have questions related to Android camera access using the Kivy `Camera` widget, please feel free to ask, and I'll be happy to assist you further.

Best regards,
tibssy

**Comment by GitProgrammerGuy32** [comment]
Ok and can I use a face detection thing with it as well as I have a pretrained  custom face detection model so can I do that ?

**Comment by GitProgrammerGuy32** [comment]
Ok so @tibssy after going through the official documentation , I ran through their camera example and it worked!, but I have to use opencv with this so  how would I do that, here is the code I used for my basic camera access without opencv:

```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
import time
Builder.load_string('''
<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
''')


class CameraClick(BoxLayout):
    def capture(self):
        '''
        Function to capture the images and give them the names
        according to their captured time and date.
        '''
        camera = self.ids['camera']
        timestr = time.strftime("%Y%m%d_%H%M%S")
        camera.export_to_png("IMG_{}.png".format(timestr))
        print("Captured")


class TestCamera(App):

    def build(self):
        return CameraClick()


TestCamera().run()
```
So My question is there a way to use OpenCV with it as I have a pre-trained ultralytics deep learning model already but it needs camera access with it so it can work with this as well?

**Comment by tibssy** [comment]
I created this repository as a starting point for Android camera access and image processing. You can use the provided code as a foundation for your project. If you haven't already, give it a try, and it should work as a good starting point to capture frames for further image processing on Android. Once the camera is working on Android, you can use Python libraries compatible with Python-for-Android for various tasks. For face detection, you can explore my example using Haar Cascades here: https://github.com/tibssy/Kivy-Android-Face-Detection

**Comment by GitProgrammerGuy32** [comment]
Hey @tibssy 

Sadly the camera access and strean cide dosent work , I am working with the current version of kivy but the camera access code dosent seem to work please look into your code and try testing it out for the updated kivy version , cause for me its not working.... and whenever I run the code I only see a black screen and such error commands in my termianl..

```
at 0x00000263E0437F50>" was accessed, it will be removed in a future version
[WARNING] Deprecated property "<BooleanProperty name=keep_ratio>" of object "<__main__.AndroidCamera object at 
0x00000263E0437F50>" was accessed, it will be removed in a future version
```
please look into your code again and try rerunning it......

**Comment by tibssy** [comment]
@GitProgrammerGuy32 

I've made significant updates to the code to ensure compatibility with the latest versions of Kivy (2.2.1) and OpenCV (4.8.0). It should now work seamlessly with the current software versions. 

Thank you for getting in touch, and please feel free to give the updated code a try. If you encounter any issues or have questions, don't hesitate to reach out. Happy coding!

**Comment by GitProgrammerGuy32** [comment]
Hey @tibssy thanks for looking over the issue and changing the code though just one question and error i was facing which was how shall I install  `jnius` to import auto class as I am not able to install using pip commands, so please list some commands to install the `jnius` python module, below is the error that I faced while Installing it.

`Fatal error in launcher: Unable to create process using '"D:\Desktop Folder\PythonApplication\kivy_venv\Scripts\python.exe"  "D:\DesktopFolder\PythonApplication\kivy_venv\Scripts\pip.exe" install pyjnius': The system cannot find the file specified.`
And please suggest where to build this buildozer file whether in collab,git actions linux or somwhere else?

Thanks in Advance 
Best Regards
Shaurya

**Comment by tibssy** [comment]
Hi @GitProgrammerGuy32,

Thank you for your message and for using my code. I'm glad to assist you.

Regarding your question about installing `jnius`, it's important to note that for an Android app, you don't need to install `jnius` on your desktop. You only need to ensure that you have the following installed on your PC for building the app:

- Python 3
- Buildozer
- Cython 0.29.36 (I've found that using the latest 3.x series can result in build failures)

As for your concern about dealing with Java classes in your code, you can easily comment out the following lines if you don't want to use them:

```
from jnius import autoclass
CameraInfo = autoclass('android.hardware.Camera$CameraInfo')
CAMERA_INDEX = {'front': CameraInfo.CAMERA_FACING_FRONT, 'back': CameraInfo.CAMERA_FACING_BACK}
```

and replace the line that sets the camera index (index = CAMERA_INDEX['back'] ) with either of these options:

```
index = 0  # for the back camera
```
or
```
index = 1  # for the front camera
```
Please keep in mind that the camera index for the front camera may not always be guaranteed to be 1; it depends on the device.

If you have more questions or need further assistance, feel free to reach out. Best of luck with your project!

**Comment by GitProgrammerGuy32** [comment]
Hey @tibssy 

Thanks for the clearance regarding the issue just wanted to understand that where do I have to build my buildozer inorder to convert it to APK and deploy it on my Android device because I have been trying to use your buildozer requirements in git actions but the buildozer always fails to build it. So where shall I build it ? Wether in Google Collab, Linux machine or somewhere else from where you have built.

Thanks in advance 
Best regards 
Shaurya

**Comment by tibssy** [comment]
Hi @GitProgrammerGuy32,

To build your app into an APK using Buildozer, it's important to note that Windows is not supported. The easiest way to create an appropriate environment for Buildozer is to set up a Linux environment within a Virtual Machine, such as VirtualBox.

I've created a video tutorial on setting up the environment, but please be aware that it might be slightly outdated as technology evolves.
You can watch the video here: 
[Linux Environment Setup for Buildozer](https://www.youtube.com/watch?v=c4tuSxSoERY).

**Comment by GitProgrammerGuy32** [comment]
Hey @tibssy had been busy with other projects for the past couple of days so didn't pay attention to this project but I had researched regarding the conversion and mailed few youtubers regarding the issue of conversion and somebody looked over the issue and made an updated video regarding it and provided the command list for conversion of kivy to APK using google collaboratory, using these commands :

CELL1 COMMANDS:
```
!sudo apt update
!sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
!pip3 install --user --upgrade Cython==0.29.33 virtualenv
```
CELL2 COMMANDS:

```
!git clone https://github.com/kivy/buildozer
%cd buildozer
!python setup.py build
!pip install -e .
%cd ..
```
CELL3 COMMANDS:

`!buildozer init`

CELL4 COMMANDS:

`!buildozer -v android debug`

And when the buildozer file was initiated I made these changes according to a tutorial:

`requirments = python3, kivy==2.2.1, kivymd==1.1.1, opencv-python==4.8.0, numpy, sdl_ttf==2.0.15, pillow `

`android.permissions = CAMERA`

And then when I tried building it using 

`!buildozer -v android debug`

It throws some weird error please look into the commands and requirements and if you need the error log as well I will definately provide you with that as well..

Thanks in advance
Best regards
Shaurya Grover
